{
 "title": "Speed Limit Service",
 "description": "Displays metrices for the speed limit service",
 "tags": [ "microservice" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "rate",
    "label": "Rate",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "kafkaTopic",
    "query": "label_values(kafka_minion_group_topic_lag, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running{pod=~\".*speedlimit.*\"})"
    }
   ]
  },
  {
   "title": "Pod Failures [last Hour]",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(changes(kube_pod_container_status_terminated_reason{pod=~\".*speedlimit.*\", reason!=\"Completed\"}[1h]))"
    }
   ]
  },
  {
   "title": "Termination Reason",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 3, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (reason) (kube_pod_container_status_last_terminated_reason{pod=~\".*speedlimit.*\", reason!=\"Completed\"})",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Pod CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{pod=~\".*speedlimit.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_memory_rss{pod=~\".*speedlimit.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate Over [$rate] of Messages Received / Sent",
   "type": "graph",
   "description": "Displays the number of messages sent and received",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (increase(speed_limit_svc_num_messages_received_total[$rate]))",
     "legendFormat": "Received {{service}}"
    },
    {
     "expr": "sum by (service) (increase(speed_limit_svc_num_speed_limits_sent_total[$rate]))",
     "legendFormat": "Sent {{service}}"
    }
   ]
  },
  {
   "title": "Rate Over [$rate] Of Errors by Error Type",
   "type": "graph",
   "description": "Shows the rate of any errors occurring in the last 5 minutes",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service)(increase(speed_limit_svc_kafka_read_failures_total[$rate]))",
     "legendFormat": "read "
    },
    {
     "expr": "sum by (service)(increase(speed_limit_svc_kafka_write_failures_total[$rate]))",
     "legendFormat": "write "
    },
    {
     "expr": "sum by (service)(increase(speed_limit_svc_num_speed_limit_api_response_errors_total[$rate]))",
     "legendFormat": "opencage"
    }
   ]
  },
  {
   "title": "Mean Open Cage Query Duration [ms]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (service)(speed_limit_svc_open_cage_query_duration_milliseconds_sum) / sum by (service)(speed_limit_svc_open_cage_query_duration_milliseconds_count)"
    }
   ]
  },
  {
   "title": "Mean Open Cage Query Duration [ms]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (service)(speed_limit_svc_cache_insert_duration_milliseconds_sum) / sum by (service)(speed_limit_svc_cache_insert_duration_milliseconds_count)"
    }
   ]
  },
  {
   "title": "KafkaTopic $kafkaTopic Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_minion_group_topic_lag{topic=\"telematics_enrichment.VehicleGpsDTO.avro18.topic\", group=\"speedLimitGroup\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Topic $kafkaTopic Partition Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_minion_group_topic_partition_lag{topic=\"telematics_enrichment.VehicleGpsDTO.avro18.topic\", group=\"speedLimitGroup\"}",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Max Open Cage Query Duration [ms]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "speed_limit_svc_max_open_cage_duration_milliseconds"
    }
   ]
  },
  {
   "title": "Max Cache Query Duration [ms]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "speed_limit_svc_max_cache_query_duration_milliseconds"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 26 },
   "targets": [
    {
     "expr": "{container_name=\"rideshur-speedlimit-service\"}"
    }
   ]
  },
  {
   "title": "Number of OpenCage Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "speed_limit_svc_num_speed_limit_api_calls_total"
    }
   ]
  },
  {
   "title": "Number of Cache Queries",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(speed_limit_svc_opencage_num_cache_results_total)"
    }
   ]
  },
  {
   "title": "Rate of Requests and Error Responses to and from OpenCage",
   "type": "graph",
   "description": "Graph shows the rate of requests made to the OpenCage API as well as the rate of errors responses by the reason for the error",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (increase(speed_limit_svc_num_speed_limit_api_calls_total[$__range]))",
     "legendFormat": "opencage requests"
    },
    {
     "expr": "sum by (reason) (increase(speed_limit_num_speed_limit_api_errors_total[$__range]))",
     "legendFormat": "error - {{reason}}"
    }
   ]
  },
  {
   "title": "Rate of Cache Hits and Misses",
   "type": "graph",
   "description": "Graph shows the rate of cache hits (speed limit cached) and misses (no speed limit cached) ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (increase(speed_limit_svc_opencage_num_cache_results_total[$__range]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Number of Limits Recorded by Speed",
   "type": "graph",
   "description": "Counts the total number of speed limits returned by the limit for all fleets and vehicles",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (speed) (speed_limit_svc_num_speed_limit_successes_total)",
     "legendFormat": "{{speed}}"
    }
   ]
  },
  {
   "title": "Number of Speed Limit Requests by Fleet",
   "type": "graph",
   "description": "Counts the number of requests made to the OpenCage API by fleet",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (fleet) (speed_limit_svc_num_speed_limit_successes_total)",
     "legendFormat": "{{fleet}}"
    }
   ]
  }
 ]
}