{
 "title": "Scoring Service",
 "tags": [ "microservice" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "rate",
    "label": "Rate",
    "query": "10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "kafkaTopic",
    "query": "label_values(kafka_minion_group_topic_lag, topic)"
   },
   {
    "name": "licence",
    "label": "licence",
    "query": "label_values(scoring_service_score_tracker, licence)"
   }
  ]
 },
 "panels": [
  {
   "title": "Running Pods",
   "type": "stat",
   "description": "Number of running pods for the scoring service",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running{pod=~\".*scoring-service.*\"})"
    }
   ]
  },
  {
   "title": "Pod Terminations Last Hour ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (increase(kube_pod_container_status_terminated_reason{pod=~\".*speedlimit.*\", reason!=\"Completed\"}[$rate]))",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "graph",
   "description": "The total CPU usage for the pod in seconds total",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{pod=~\".*scoring-service.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_memory_rss{pod=~\".*scoring-service.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate Over [$rate] of Messages Sent and Received",
   "type": "graph",
   "description": "The rate of messages received and sent via kafka",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service)(increase(scoring_service_num_received_messages_total[$rate]))",
     "legendFormat": "received"
    },
    {
     "expr": "sum by (service)(increase(scoring_service_num_sent_messages_total[$rate]))",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Rate Of Messages Received With No Trip Distance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service)(increase(scoring_service_num_trips_received_no_distance_total[$rate]))"
    }
   ]
  },
  {
   "title": "Rate of Scoring Successes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service)(increase(scoring_service_num_score_successes_total[$rate]))",
     "legendFormat": "successes"
    }
   ]
  },
  {
   "title": "Rate Over [$rate] of Errors by Error Type",
   "type": "graph",
   "description": "The rate of errors occurring during normal operation by error type",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (increase(scoring_service_num_kafka_read_failures_total[$rate]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum by (service) (increase(scoring_service_num_kafka_write_failures_total[$rate]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum by (service) (increase(scoring_service_num_score_failures_total[$rate]))",
     "legendFormat": "score"
    },
    {
     "expr": "sum by (service) (increase(scoring_service_num_avro_errors_total[$rate]))",
     "legendFormat": "avro"
    },
    {
     "expr": "sum by (service) (increase(scoring_service_num_graphql_errors_total[$rate]))",
     "legendFormat": "graphql"
    }
   ]
  },
  {
   "title": "Kafka $kafkaTopic Topic Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_minion_group_topic_lag{topic=\"service_trip_enrichment.TripInfoDTO.avro18.topic\", group=\"scoringGroup\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Topic $kafkaTopic Partition Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_minion_group_topic_partition_lag{topic=\"service_trip_enrichment.TripInfoDTO.avro18.topic\"}",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Score by Fleet",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (fleet)(scoring_service_score_tracker)",
     "legendFormat": "{{fleet}}"
    }
   ]
  },
  {
   "title": "Average Score by Licence",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (licence)(scoring_service_score_tracker{licence=~\"$licence\"})",
     "legendFormat": "{{licence}}"
    }
   ]
  },
  {
   "title": "Score Tracker",
   "type": "graph",
   "description": "Tracks the change in driver score over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (licence)(scoring_service_score_tracker{licence=~\"$licence\"})",
     "legendFormat": "{{licence}}"
    }
   ]
  },
  {
   "title": "Relative Risk Tracker",
   "type": "graph",
   "description": "Tracks the change in total relative risk over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (licence)(scoring_service_relative_risk_tracker{licence=~\"$licence\"})",
     "legendFormat": "{{licence}}"
    }
   ]
  }
 ]
}