{
 "title": "Secor Dashboard",
 "time": { "from": "2021-02-04T12:50:04.812Z", "to": "2021-02-04T13:19:28.077Z" },
 "panels": [
  {
   "title": "Messages with incorrect format in last 15 min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(consumer_message_errors_count_total[15m])"
    }
   ]
  },
  {
   "title": "Files uploaded in last hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(uploader_file_uploads_count_total[1h])"
    }
   ]
  },
  {
   "title": "Total files uploaded",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "uploader_file_uploads_count_total"
    }
   ]
  },
  {
   "title": "Total througput increase in last 15 min(B)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(consumer_throughput_bytes_total[15m])"
    }
   ]
  },
  {
   "title": "Total throughput (kB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consumer_throughput_bytes_total/1024"
    }
   ]
  }
 ]
}